/* lookup tables (matches what is maintained by template replication) */
select  rtrim('announcements          '), count(*) from announcements
union select  rtrim('clinicLookup          '), count(*) from clinicLookup 
union select  rtrim('cohortAsort           '), count(*) from cohortAsort
union select  rtrim('concept               '), count(*) from concept   
union select  rtrim('concept_class         '), count(*) from concept_class 
union select  rtrim('concept_datatype      '), count(*) from concept_datatype   
union select  rtrim('concept_name          '), count(*) from concept_name          
union select  rtrim('conditionLookup       '), count(*) from conditionLookup        
union select  rtrim('conditionOrder        '), count(*) from conditionOrder         
union select  rtrim('discReasonLookup      '), count(*) from discReasonLookup       
union select  rtrim('drugGroupLookup       '), count(*) from drugGroupLookup         
union select  rtrim('drugLookup            '), count(*) from drugLookup             
union select  rtrim('drugVersionOrder      '), count(*) from drugVersionOrder       
union select  rtrim('encTypeLookup         '), count(*) from encTypeLookup          
union select  rtrim('immunizationLookup    '), count(*) from immunizationLookup     
union select  rtrim('immunizationRendering '), count(*) from immunizationRendering
union select  rtrim('labelLookup           '), count(*) from labelLookup     
union select  rtrim('labLookup             '), count(*) from labLookup   
union select  rtrim('nastadLookup          '), count(*) from nastadLookup 
union select  rtrim('networkLookup         '), count(*) from networkLookup                  
union select  rtrim('patientStatusLookup   '), count(*) from patientStatusLookup    
union select  rtrim('pedLabsLookup         '), count(*) from pedLabsLookup          
union select  rtrim('pedLabsRendering      '), count(*) from pedLabsRendering       
union select  rtrim('referralLookup        '), count(*) from referralLookup 
union select  rtrim('regimen               '), count(*) from regimen        
union select  rtrim('riskLookup            '), count(*) from riskLookup             
union select  rtrim('riskOrder             '), count(*) from riskOrder
go       
/* all tables of interest in the database */
select  rtrim('appVersion                            '), count(*) from appVersion                             
union select  rtrim('concept                               '), count(*) from concept                                                                               
union select  rtrim('concept_class                         '), count(*) from concept_class                          
union select  rtrim('concept_datatype                      '), count(*) from concept_datatype                                                 
union select  rtrim('concept_name                          '), count(*) from concept_name                                                      
union select  rtrim('drugs                                 '), count(*) from drugs                                   
union select  rtrim('encounter                             '), count(*) from encounter                                                                                       
union select  rtrim('obs                                   '), count(*) from obs                                                                   
union select  rtrim('adherenceCounseling                   '), count(*) from adherenceCounseling                    
union select  rtrim('allergies                             '), count(*) from allergies                              
union select  rtrim('allowedDisclosures                    '), count(*) from allowedDisclosures                                              
union select  rtrim('arvAndPregnancy                       '), count(*) from arvAndPregnancy                        
union select  rtrim('arvEnrollment                         '), count(*) from arvEnrollment                                                      
union select  rtrim('buddies                               '), count(*) from buddies                                                               
union select  rtrim('clinicLookup                          '), count(*) from clinicLookup                                                                                  
union select  rtrim('comprehension                         '), count(*) from comprehension                          
union select  rtrim('conditionLookup                       '), count(*) from conditionLookup                        
union select  rtrim('conditionOrder                        '), count(*) from conditionOrder                         
union select  rtrim('conditions                            '), count(*) from conditions                             
union select  rtrim('discEnrollment                        '), count(*) from discEnrollment                         
union select  rtrim('discReasonLookup                      '), count(*) from discReasonLookup                                                                               
union select  rtrim('drugGroupLookup                       '), count(*) from drugGroupLookup                                         
union select  rtrim('drugLookup                            '), count(*) from drugLookup                             
union select  rtrim('drugSummary                           '), count(*) from drugSummary                            
union select  rtrim('drugTable                             '), count(*) from drugTable                              
union select  rtrim('drugVersionOrder                      '), count(*) from drugVersionOrder                       
union select  rtrim('drugs                                 '), count(*) from drugs                                                        
union select  rtrim('eligibility                           '), count(*) from eligibility                            
union select  rtrim('encTypeLookup                         '), count(*) from encTypeLookup                                                                                                                         
union select  rtrim('followupTreatment                     '), count(*) from followupTreatment                                                     
union select  rtrim('homeCareVisits                        '), count(*) from homeCareVisits                         
union select  rtrim('householdComp                         '), count(*) from householdComp                          
union select  rtrim('immunizationLookup                    '), count(*) from immunizationLookup                     
union select  rtrim('immunizationRendering                 '), count(*) from immunizationRendering                  
union select  rtrim('immunizations                         '), count(*) from immunizations                          
union select  rtrim('labLookup                             '), count(*) from labLookup                                                         
union select  rtrim('labs                                  '), count(*) from labs                                                            
union select  rtrim('medicalEligARVs                       '), count(*) from medicalEligARVs                                                                                 
union select  rtrim('needsAssessment                       '), count(*) from needsAssessment                                            
union select  rtrim('patient                               '), count(*) from patient                                
union select  rtrim('patientEducation                      '), count(*) from patientEducation                                               
union select  rtrim('patientStatusLookup                   '), count(*) from patientStatusLookup                    
union select  rtrim('patientStatusTemp                     '), count(*) from patientStatusTemp                      
union select  rtrim('pedHistory                            '), count(*) from pedHistory                             
union select  rtrim('pedLabs                               '), count(*) from pedLabs                                
union select  rtrim('pedLabsLookup                         '), count(*) from pedLabsLookup                          
union select  rtrim('pedLabsRendering                      '), count(*) from pedLabsRendering                                                  
union select  rtrim('prescriptionOtherFields               '), count(*) from prescriptionOtherFields                
union select  rtrim('prescriptions                         '), count(*) from prescriptions                          
union select  rtrim('referralLookup                        '), count(*) from referralLookup                         
union select  rtrim('referrals                             '), count(*) from referrals                              
union select  rtrim('regimen                               '), count(*) from regimen                                                         
union select  rtrim('replicationRead                       '), count(*) from replicationRead                                               
union select  rtrim('riskAssessments                       '), count(*) from riskAssessments                        
union select  rtrim('riskLookup                            '), count(*) from riskLookup                             
union select  rtrim('riskOrder                             '), count(*) from riskOrder                                                                                                                    
union select  rtrim('tbStatus                              '), count(*) from tbStatus
go
