<?php

define('TB_QUAL',
       "drugname in ('ethambutol', 'isoniazid', 'pyrazinamide', 'rifampicine', 'streptomycine')");

$query = array (
	//  had test/was a patient
	"5030" => array (
		// this query establishes the first time each patient ever had the specified test (*temp)
		// Does it need to capture test WITHIN THE BUCKET???
		"select patientid, min(visitdate), count(distinct visitdate) from \$labtest group by patientid",
		// this and subsequent queries determine active/new patients in each six month bucket relative to the end date for the bucket
		"select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2004-01-01') and visitdate between '2004-01-01' and '2004-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2004-07-01') and visitdate between '2004-07-01' and '2004-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2005-01-01') and visitdate between '2005-01-01' and '2005-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2005-07-01') and visitdate between '2005-07-01' and '2005-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2006-01-01') and visitdate between '2006-01-01' and '2006-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2006-07-01') and visitdate between '2006-07-01' and '2006-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2007-01-01') and visitdate between '2007-01-01' and '2007-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2007-07-01') and visitdate between '2007-07-01' and '2007-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2008-01-01') and visitdate between '2008-01-01' and '2008-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2008-07-01') and visitdate between '2008-07-01' and '2008-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2009-01-01') and visitdate between '2009-01-01' and '2009-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2009-07-01') and visitdate between '2009-07-01' and '2009-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2010-01-01') and visitdate between '2010-01-01' and '2010-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2010-07-01') and visitdate between '2010-07-01' and '2010-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2011-01-01') and visitdate between '2011-01-01' and '2011-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2011-07-01') and visitdate between '2011-07-01' and '2011-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2012-01-01') and visitdate between '2012-01-01' and '2012-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2012-07-01') and visitdate between '2012-07-01' and '2012-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)"
	),
	//  up to date on test/was a patient
	"5031" => array (
		// this query establishes the most recent occurance of the specified test for each patient (*temp)
		"select patientid, max(visitdate), count(distinct visitdate) from \$labtest group by patientid",
		// this query establishes the earliest visit within the bucket for each active patient, but is not lab specific
		// separates patients on meds from patients not on meds relative to end of each bucket date, first patients not on ART
		"select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2004-01-01') and patientid not in (select patientid from pepfarTable where visitdate between '2004-01-01' and '2004-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2004-01-01' and '2004-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2004-07-01') and patientid not in (select patientid from pepfarTable where visitdate between '2004-07-01' and '2004-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2004-07-01' and '2004-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2005-01-01') and patientid not in (select patientid from pepfarTable where visitdate between '2005-01-01' and '2005-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2005-01-01' and '2005-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2005-07-01') and patientid not in (select patientid from pepfarTable where visitdate between '2005-07-01' and '2005-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2005-07-01' and '2005-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2006-01-01') and patientid not in (select patientid from pepfarTable where visitdate between '2006-01-01' and '2006-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2006-01-01' and '2006-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2006-07-01') and patientid not in (select patientid from pepfarTable where visitdate between '2006-07-01' and '2006-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2006-07-01' and '2006-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2007-01-01') and patientid not in (select patientid from pepfarTable where visitdate between '2007-01-01' and '2007-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2007-01-01' and '2007-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2007-07-01') and patientid not in (select patientid from pepfarTable where visitdate between '2007-07-01' and '2007-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2007-07-01' and '2007-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2008-01-01') and patientid not in (select patientid from pepfarTable where visitdate between '2008-01-01' and '2008-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2008-01-01' and '2008-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2008-07-01') and patientid not in (select patientid from pepfarTable where visitdate between '2008-07-01' and '2008-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2008-07-01' and '2008-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2009-01-01') and patientid not in (select patientid from pepfarTable where visitdate between '2009-01-01' and '2009-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2009-01-01' and '2009-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2009-07-01') and patientid not in (select patientid from pepfarTable where visitdate between '2009-07-01' and '2009-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2009-07-01' and '2009-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2010-01-01') and patientid not in (select patientid from pepfarTable where visitdate between '2010-01-01' and '2010-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2010-01-01' and '2010-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2010-07-01') and patientid not in (select patientid from pepfarTable where visitdate between '2010-07-01' and '2010-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2010-07-01' and '2010-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2011-01-01') and patientid not in (select patientid from pepfarTable where visitdate between '2011-01-01' and '2011-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2011-01-01' and '2011-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2011-07-01') and patientid not in (select patientid from pepfarTable where visitdate between '2011-07-01' and '2011-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2011-07-01' and '2011-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2012-01-01') and patientid not in (select patientid from pepfarTable where visitdate between '2012-01-01' and '2012-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2012-01-01' and '2012-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 0 from v_patients where patientid not in (select patientid from discTable where discDate > '2012-07-01') and patientid not in (select patientid from pepfarTable where visitdate between '2012-07-01' and '2012-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2012-07-01' and '2012-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		// starting here, add patients on ART
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2004-01-01') and patientid in (select patientid from pepfarTable where visitdate between '2004-03-01' and '2004-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2004-03-01' and '2004-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2004-07-01') and patientid in (select patientid from pepfarTable where visitdate between '2004-09-01' and '2004-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2004-09-01' and '2004-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2005-01-01') and patientid in (select patientid from pepfarTable where visitdate between '2005-03-01' and '2005-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2005-03-01' and '2005-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2005-07-01') and patientid in (select patientid from pepfarTable where visitdate between '2005-09-01' and '2005-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2005-09-01' and '2005-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2006-01-01') and patientid in (select patientid from pepfarTable where visitdate between '2006-03-01' and '2006-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2006-03-01' and '2006-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2006-07-01') and patientid in (select patientid from pepfarTable where visitdate between '2006-09-01' and '2006-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2006-09-01' and '2006-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2007-01-01') and patientid in (select patientid from pepfarTable where visitdate between '2007-03-01' and '2007-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2007-03-01' and '2007-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2007-07-01') and patientid in (select patientid from pepfarTable where visitdate between '2007-09-01' and '2007-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2007-09-01' and '2007-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2008-01-01') and patientid in (select patientid from pepfarTable where visitdate between '2008-03-01' and '2008-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2008-03-01' and '2008-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2008-07-01') and patientid in (select patientid from pepfarTable where visitdate between '2008-09-01' and '2008-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2008-09-01' and '2008-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2009-01-01') and patientid in (select patientid from pepfarTable where visitdate between '2009-03-01' and '2009-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2009-03-01' and '2009-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2009-07-01') and patientid in (select patientid from pepfarTable where visitdate between '2009-09-01' and '2009-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2009-09-01' and '2009-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2010-01-01') and patientid in (select patientid from pepfarTable where visitdate between '2010-03-01' and '2010-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2010-03-01' and '2010-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2010-07-01') and patientid in (select patientid from pepfarTable where visitdate between '2010-09-01' and '2010-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2010-09-01' and '2010-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2011-01-01') and patientid in (select patientid from pepfarTable where visitdate between '2011-03-01' and '2011-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2011-03-01' and '2011-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2011-07-01') and patientid in (select patientid from pepfarTable where visitdate between '2011-09-01' and '2011-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2011-09-01' and '2011-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2012-01-01') and patientid in (select patientid from pepfarTable where visitdate between '2012-03-01' and '2012-06-30' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2012-03-01' and '2012-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), 1 from v_patients where patientid not in (select patientid from discTable where discDate > '2012-07-01') and patientid in (select patientid from pepfarTable where visitdate between '2012-09-01' and '2012-12-31' AND (forPepPmtct = 0 OR forPepPmtct IS NULL)) and visitdate between '2012-09-01' and '2012-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)"
	),
	//  received art/qualified for art
	"5040" => array (
		// earliest date a patient received ART
		"select patientid, min(visitdate), count(distinct visitdate) from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL) group by patientid",
		// earliest date a patient qualified for ART
		//"select patientid, min(visitDate) as visitdate, count(distinct visitdate) as visitcount from v_patients where patientid in (select patientid from cd4Table where cd4 < 350 and cd4 != 0) or patientid in (select patientid from v_labsCompleted where testnameen = 'lymphocytes' and result <= '1200' and result != '') or (patientid in (select patientid from cd4Table where cd4 < 350 and cd4 != 0) and patientid in (select patientid from v_conditions where conditionGroup = 3)) or patientid in (select patientid from v_conditions where conditionGroup = 4) or patientid in (select distinct patientid from medicalEligARVs where medElig in (1,2)) group by patientid"
                "select p.patientID, min(e.visitDate) as visitdate, count(distinct p.visitDate) as visitcount from v_patients p, eligibility e where p.patientID = e.patientid and e.reason in ('cd4LT200', 'tlcLT1200', 'WHOIII', 'WHOIV', 'medEligHAART', 'estPrev', 'former', 'eligByAge', 'eligByCond', 'eligPcr', 'WHOIII-2', 'WHOIIICond') and e.criteriaVersion = 1 group by p.patientID",
                "select p.patientID, min(e.visitDate) as visitdate, count(distinct p.visitDate) as visitcount from v_patients p, eligibility e where p.patientID = e.patientid and e.reason in ('cd4LT200', 'tlcLT1200', 'WHOIII', 'WHOIV', 'medEligHAART', 'estPrev', 'former', 'eligByAge', 'eligByCond', 'eligPcr', 'WHOIII-2', 'WHOIIICond') and e.criteriaVersion = 2 group by p.patientID",
                "select p.patientID, min(e.visitDate) as visitdate, count(distinct p.visitDate) as visitcount from v_patients p, eligibility e where p.patientID = e.patientid and e.reason in ('OptionB+') and e.criteriaVersion = 3 group by p.patientID"
/*
                "select patientID, min(visitdate) as visitdate, count(distinct visitdate) as visitcount from v_patients where patientID in (
        select patientid from cd4Table where cd4 < 350 and cd4 != 0
        union all
	select patientID from patient where isPediatric = 1 and patientID in (select patientID from v_labsCompleted where testNameEn = 'lymphocytes' and result <= '1200' and result != '')
	union all
	select patientID from patient where isPediatric = 1 and patientID in (select patientID from v_conditions where whoStage = 'Stage III') and patientID in (select patientID from cd4Table where cd4 < 350 and cd4 != 0)
        union all
        select patientID from patient where isPediatric = 1 and patientID in (select s.patientID from symptoms s, encounter e where s.pedSympWhoWtLoss2 = 1 and e.encStatus < 255 and s.patientID = e.patientID and s.siteCode = e.siteCode and s.visitDateDd = e.visitDateDd and s.visitDateMm = e.visitDateMm and s.visitDateYy = e.visitDateYy and s.seqNum = e.seqNum) and patientID in (select patientID from cd4Table where cd4 < 350 and cd4 != 0)
        union all
        select patientID from patient where isPediatric = 1 and patientID in (select m.patientID from medicalEligARVs m, encounter e where m.currentHivStage in (4, 5, 6, 7, 12, 13, 14, 15) and e.encStatus < 255 and m.patientID = e.patientID and m.siteCode = e.siteCode and m.visitDateDd = e.visitDateDd and m.visitDateMm = e.visitDateMm and m.visitDateYy = e.visitDateYy and m.seqNum = e.seqNum) and patientID in (select patientID from cd4Table where cd4 < 350 and cd4 != 0)
	union all
	select patientID from patient where isPediatric = 1 and patientID in (select patientID from v_conditions where whoStage = 'Stage IV')
	union all
        select patientID from patient where isPediatric = 1 and patientID in (select s.patientID from symptoms s, encounter e where s.pedSympWhoWtLoss3 = 1 and e.encStatus < 255 and s.patientID = e.patientID and s.siteCode = e.siteCode and s.visitDateDd = e.visitDateDd and s.visitDateMm = e.visitDateMm and s.visitDateYy = e.visitDateYy and s.seqNum = e.seqNum)
	union all
        select patientID from patient where isPediatric = 1 and patientID in (select m.patientID from medicalEligARVs m, encounter e where m.currentHivStage > 7 and e.encStatus < 255 and m.patientID = e.patientID and m.siteCode = e.siteCode and m.visitDateDd = e.visitDateDd and m.visitDateMm = e.visitDateMm and m.visitDateYy = e.visitDateYy and m.seqNum = e.seqNum)
	union all
	select patientID from patient where isPediatric = 1 and patientID in (select patientID from v_medicalEligARVs where medElig in (1, 3, 5, 7))
	union all
	select patientID from patient where isPediatric = 1 and patientID in (select patientID from v_medicalEligARVs where pedMedEligCd4Cnt = 1 or pedMedEligTlc = 1 or pedMedEligWho3 = 1 or pedMedEligWho4 = 1 or pedMedEligPmtct = 1 or pedMedEligFormerTherapy = 1)
        union all
	select patientID from patient where (isPediatric != 1 or isPediatric is NULL) and patientID in (select patientID from v_labsCompleted where testNameEn = 'lymphocytes' and result <= '1200' and result != '')
	union all
	select patientID from patient where (isPediatric != 1 or isPediatric is NULL) and patientID in (select patientID from v_conditions where whoStage = 'Stage III') and patientID in (select patientID from cd4Table where cd4 < 350 and cd4 != 0)
        union all
        select patientID from patient where (isPediatric != 1 or isPediatric is NULL) and patientID in (select s.patientID from symptoms s, encounter e where (s.weightLossPlusTenPercMo = 1 or s.feverPlusMo = 1 or s.diarrheaPlusMo = 1) and e.encStatus < 255 and s.patientID = e.patientID and s.siteCode = e.siteCode and s.visitDateDd = e.visitDateDd and s.visitDateMm = e.visitDateMm and s.visitDateYy = e.visitDateYy and s.seqNum = e.seqNum) and patientID in (select patientID from cd4Table where cd4 < 350 and cd4 != 0)
        union all
        select patientID from patient where (isPediatric != 1 or isPediatric is NULL) and patientID in (select m.patientID from medicalEligARVs m, encounter e where e.formVersion = 1 and m.currentHivStage in (4, 5, 6, 7, 12, 13, 14, 15) and e.encStatus < 255 and m.patientID = e.patientID and m.siteCode = e.siteCode and m.visitDateDd = e.visitDateDd and m.visitDateMm = e.visitDateMm and m.visitDateYy = e.visitDateYy and m.seqNum = e.seqNum) and patientID in (select patientID from cd4Table where cd4 < 350 and cd4 != 0)
	union all
	select patientID from patient where (isPediatric != 1 or isPediatric is NULL) and patientID in (select patientID from v_conditions where whoStage = 'Stage IV')
        union all
        select patientID from patient where (isPediatric != 1 or isPediatric is NULL) and patientID in (select s.patientID from symptoms s, encounter e where s.wtLossTenPercWithDiarrMo = 1 and e.encStatus < 255 and s.patientID = e.patientID and s.siteCode = e.siteCode and s.visitDateDd = e.visitDateDd and s.visitDateMm = e.visitDateMm and s.visitDateYy = e.visitDateYy and s.seqNum = e.seqNum)
        union all
        select patientID from patient where (isPediatric != 1 or isPediatric is NULL) and patientID in (select m.patientID from medicalEligARVs m, encounter e where (((e.formVersion != 1 or e.formVersion is NULL) and m.currentHivStage > 3) or m.currentHivStage > 7) and e.encStatus < 255 and m.patientID = e.patientID and m.siteCode = e.siteCode and m.visitDateDd = e.visitDateDd and m.visitDateMm = e.visitDateMm and m.visitDateYy = e.visitDateYy and m.seqNum = e.seqNum)
	union all
	select patientID from patient where (isPediatric != 1 or isPediatric is NULL) and patientID in (select m.patientID from medicalEligARVs m, encounter e where e.encStatus < 255 and e.siteCode = m.siteCode and e.visitDateDd = m.visitDateDd and e.visitDateMm = m.visitDateMm and e.visitDateYy = m.visitDateYy and e.patientID = m.patientID and e.seqNum = m.seqNum and ((medElig in (1, 2, 3, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15) and (e.formVersion != 1 or e.formVersion is NULL)) or (medElig in (1, 3, 5, 7) and e.formVersion = 1)))
	union all
	select patientID from patient where (isPediatric != 1 or isPediatric is NULL) and patientID in (select patientID from v_medicalEligARVs where  (cd4LT200 = 1 or tlcLT1200 = 1 or WHOIII = 1 or WHOIV = 1 or PMTCT = 1 or formerARVtherapy = 1 or PEP = 1 or medEligHAART = 1))) group by patientID"
*/
	),
	//  ctx initiation/qualification
	"5041" => array (
		"select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) group by patientid",
//		"select patientid, min(visitdate), count(distinct visitdate) from cd4Table where cd4 < 350 group by patientid",
//		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where (conditionNameEn like '%thrush%' or conditionNameEn like 'Oesphagites%' or conditionGroup = 4) group by patientid"
                "select p.patientID, min(e.visitDate), count(distinct p.visitdate) from v_patients p, eligibility e where p.patientID = e.patientID and e.reason in ('tmsAdult', 'tmsChildInfected', 'tmsChildExposed') group by p.patientID"
/*
                "select patientID, min(visitdate), count(distinct visitdate) from v_patients where patientID in (
        select t.patientID from patient t where t.patientID in (select patientID from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL)) and t.patientID in (select patientID from cd4Table where cd4 < 350 and cd4 != 0)
        union all
        select t.patientID from patient t where t.patientID in (select patientID from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL)) and t.patientID in (select patientID from v_conditions where whoStage = 'Stage IV')
        union all
        select t.patientID from patient t where t.patientID in (select patientID from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL)) and t.patientID in (select m.patientID from medicalEligARVs m, encounter e, patient p where e.encStatus < 255 and (((e.formVersion != 1 or e.formVersion is NULL) and (p.isPediatric != 1 or p.isPediatric is NULL) and m.currentHivStage < 3) or m.currentHivStage < 7) and m.patientID = e.patientID and p.patientID = e.patientID and m.siteCode = e.siteCode and m.visitDateDd = e.visitDateDd and m.visitDateMm = e.visitDateMm and m.visitDateYy = e.visitDateYy and m.seqNum = e.seqNum)
        union all
        select t.patientID from patient t where t.patientID in (select patientID from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL)) and t.patientID in (select s.patientID from symptoms s, encounter e, patient p where e.encStatus < 255 and ((p.isPediatric = 1 and s.pedSympWhoWtLoss3 = 1) or ((p.isPediatric != 1 or p.isPediatric is NULL) and s.wtLossTenPercWithDiarrMo = 1)) and s.patientID = e.patientID and p.patientID = e.patientID and s.siteCode = e.siteCode and s.visitDateDd = e.visitDateDd and s.visitDateMm = e.visitDateMm and s.visitDateYy = e.visitDateYy and s.seqNum = e.seqNum)
        union all
        select t.patientID from patient t where t.patientID in (select patientID from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL)) and t.patientID in (select patientID from v_conditions where conditionID in (13, 196, 415) and visitdate between dateadd(mm, -6, getdate()) and getdate())
        union all
        select t.patientID from patient t where t.patientID not in (select patientID from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL)) and t.patientID in (select patientID from cd4Table where cd4 < 350 and cd4 != 0 and visitdate between dateadd(mm, -6, getdate()) and getdate())
        union all
        select t.patientID from patient t where t.patientID not in (select patientID from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL)) and t.patientID in (select patientID from v_conditions where (whoStage = 'Stage IV' or conditionID in (13, 196, 415)))
        union all
        select t.patientID from patient t where t.patientID not in (select patientID from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL)) and t.patientID in (select m.patientID from medicalEligARVs m, encounter e, patient p where e.encStatus < 255 and (((e.formVersion != 1 or e.formVersion is NULL) and (p.isPediatric != 1 or p.isPediatric is NULL) and m.currentHivStage > 3) or m.currentHivStage > 7) and m.patientID = e.patientID and p.patientID = e.patientID and m.siteCode = e.siteCode and m.visitDateDd = e.visitDateDd and m.visitDateMm = e.visitDateMm and m.visitDateYy = e.visitDateYy and m.seqNum = e.seqNum)
        union all
        select t.patientID from patient t where t.patientID not in (select patientID from pepfarTable where (forPepPmtct = 0 OR forPepPmtct IS NULL)) and t.patientID in (select s.patientID from symptoms s, encounter e, patient p where e.encStatus < 255 and ((p.isPediatric = 1 and s.pedSympWhoWtLoss3 = 1) or ((p.isPediatric != 1 or p.isPediatric is NULL) and s.wtLossTenPercWithDiarrMo = 1)) and s.patientID = e.patientID and p.patientID = e.patientID and s.siteCode = e.siteCode and s.visitDateDd = e.visitDateDd and s.visitDateMm = e.visitDateMm and s.visitDateYy = e.visitDateYy and s.seqNum = e.seqNum)) group by patientID"
*/
	),
	// ctx initiation/continuation
	"5042" => array (
		"select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) group by patientid",
		"select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2004-05-01' and '2004-06-30' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2004-11-01' and '2004-12-31' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2005-05-01' and '2005-06-30' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2005-11-01' and '2005-12-31' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2006-05-01' and '2006-06-30' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2006-11-01' and '2006-12-31' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2007-05-01' and '2007-06-30' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2007-11-01' and '2007-12-31' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2008-05-01' and '2008-06-30' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2008-11-01' and '2008-12-31' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2009-05-01' and '2009-06-30' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2009-11-01' and '2009-12-31' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2010-05-01' and '2010-06-30' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2010-11-01' and '2010-12-31' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2011-05-01' and '2011-06-30' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2011-11-01' and '2011-12-31' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2012-05-01' and '2012-06-30' group by patientid having count(distinct visitDate) >= 1",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_medsDispensed where drugID in (9, 69, 70) and visitdate between '2012-11-01' and '2012-12-31' group by patientid having count(distinct visitDate) >= 1"
	),
	// TB treatment initiation/qualification
	"5043" => array (
		"select patientid, min(visitdate), count(distinct visitdate) from v_prescriptions where " . TB_QUAL . " group by patientid having count(distinct drugname) >= 4",
		"select patientid, min(visitdate), count(distinct visitdate) from v_labsCompleted where (testnameen = 'Chest X-Ray' and resultAbnormal = 1) or (testnameen = 'sputum' and resultAbnormal = 1) group by patientid",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionnameen like '%tb%' group by patientid",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_symptoms where (cough3WeeksEqualMore = 1 or ((cough3WeeksLess = 1 or cough = 1) and expectoration = 1) or hemoptysie = 1) and nightsweats = 1 and (feverLessMo = 1 or feverPlusMo = 1) group by patientid"
	),
	// TB treatment initiation/continuation
	"5044" => array (
		// first start of tb treatment over all buckets
		"select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " group by patientid having count(distinct drugname) >= 4",
		// at least one dispense of 2 tb drugs in last two months of period
		"select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2004-05-01' and '2004-06-30' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2004-11-01' and '2004-12-31' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2005-05-01' and '2005-06-30' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2005-11-01' and '2005-12-31' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2006-05-01' and '2006-06-30' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2006-11-01' and '2006-12-31' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2007-05-01' and '2007-06-30' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2007-11-01' and '2007-12-31' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2008-05-01' and '2008-06-30' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2008-11-01' and '2008-12-31' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2009-05-01' and '2009-06-30' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2009-11-01' and '2009-12-31' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2010-05-01' and '2010-06-30' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2010-11-01' and '2010-12-31' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2011-05-01' and '2011-06-30' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2011-11-01' and '2011-12-31' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2012-05-01' and '2012-06-30' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2",
		"insert into temp1" . $user . " select patientid, min(visitdate), count(distinct visitdate) from drugTable d, drugLookup l where d.drugID = l.drugID and  " . TB_QUAL . " and visitdate between '2012-11-01' and '2012-12-31' group by patientid having count(distinct visitDate) >= 1 and count(distinct drugname) >= 2"
	),
	// PCP Dx in period/active patient in period
	"5045" => array (
		// patient's first Dx of PCP (*temp)
		"select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2004-01-01' and '2004-06-30' group by patientid",
		// this and subsequent queries determine active/new patients in each six month bucket relative to the end date for the bucket
		"select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2004-01-01') and visitdate between '2004-01-01' and '2004-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2004-07-01') and visitdate between '2004-07-01' and '2004-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2005-01-01') and visitdate between '2005-01-01' and '2005-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2005-07-01') and visitdate between '2005-07-01' and '2005-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2006-01-01') and visitdate between '2006-01-01' and '2006-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2006-07-01') and visitdate between '2006-07-01' and '2006-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2007-01-01') and visitdate between '2007-01-01' and '2007-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2007-07-01') and visitdate between '2007-07-01' and '2007-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2008-01-01') and visitdate between '2008-01-01' and '2008-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2008-07-01') and visitdate between '2008-07-01' and '2008-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2009-01-01') and visitdate between '2009-01-01' and '2009-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2009-07-01') and visitdate between '2009-07-01' and '2009-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2010-01-01') and visitdate between '2010-01-01' and '2010-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2010-07-01') and visitdate between '2010-07-01' and '2010-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2011-01-01') and visitdate between '2011-01-01' and '2011-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2011-07-01') and visitdate between '2011-07-01' and '2011-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2012-01-01') and visitdate between '2012-01-01' and '2012-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2012-07-01') and visitdate between '2012-07-01' and '2012-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		// subsequent first Dx after intake visit
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2004-07-01' and '2004-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2005-01-01' and '2005-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2005-07-01' and '2005-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2006-01-01' and '2006-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2006-07-01' and '2006-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2007-01-01' and '2007-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2007-07-01' and '2007-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2008-01-01' and '2008-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2008-07-01' and '2008-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2009-01-01' and '2009-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2009-07-01' and '2009-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2010-01-01' and '2010-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2010-07-01' and '2010-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2011-01-01' and '2011-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2011-07-01' and '2011-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2012-01-01' and '2012-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pcp', 'PneumUnknownCause') and visitdate between '2012-07-01' and '2012-12-31' group by patientid",
		// now delete from *temp if Dx isn't AFTER intake visit
		"delete from temp" . $user . " from temp" . $user . " t, encValid e where t.patientid = e.patientid and e.encountertype = 1 and t.maxDate <= e.visitdate"
	),
	// TB Dx in period/active patients in period
	"5046" => array (
		// patient's Dx of TB in period(*temp)
		"select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2004-01-01' and '2004-06-30' group by patientid",
		// this and following queries determine active/new patients in each six month bucket relative to the end date for the bucket
		"select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2004-01-01') and visitdate between '2004-01-01' and '2004-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2004-07-01') and visitdate between '2004-07-01' and '2004-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2005-01-01') and visitdate between '2005-01-01' and '2005-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2005-07-01') and visitdate between '2005-07-01' and '2005-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2006-01-01') and visitdate between '2006-01-01' and '2006-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2006-07-01') and visitdate between '2006-07-01' and '2006-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2007-01-01') and visitdate between '2007-01-01' and '2007-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2007-07-01') and visitdate between '2007-07-01' and '2007-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2008-01-01') and visitdate between '2008-01-01' and '2008-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2008-07-01') and visitdate between '2008-07-01' and '2008-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2009-01-01') and visitdate between '2009-01-01' and '2009-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2009-07-01') and visitdate between '2009-07-01' and '2009-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2010-01-01') and visitdate between '2010-01-01' and '2010-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2010-07-01') and visitdate between '2010-07-01' and '2010-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2011-01-01') and visitdate between '2011-01-01' and '2011-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2011-07-01') and visitdate between '2011-07-01' and '2011-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2012-01-01') and visitdate between '2012-01-01' and '2012-06-30' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (5,6)",
		"insert into temp1" . $user . " select patientid, min(visitDate), count(distinct visitdate) from v_patients where patientid not in (select patientid from discTable where discDate > '2012-07-01') and visitdate between '2012-07-01' and '2012-12-31' group by patientid having count(distinct visitDate) > 1 or month(min(visitdate)) in (11,12)",
		// more Dx in period
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2004-07-01' and '2004-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2005-01-01' and '2005-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2005-07-01' and '2005-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2006-01-01' and '2006-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2006-07-01' and '2006-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2007-01-01' and '2007-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2007-07-01' and '2007-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2008-01-01' and '2008-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2008-07-01' and '2008-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2009-01-01' and '2009-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2009-07-01' and '2009-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2010-01-01' and '2010-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2010-07-01' and '2010-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2011-01-01' and '2011-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2011-07-01' and '2011-12-31' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2012-01-01' and '2012-06-30' group by patientid",
		"insert into temp" . $user . " select patientid, min(visitdate), count(distinct visitdate) from v_conditions where conditionCode in ('pulmTB', 'extrapulmTB') and visitdate between '2012-07-01' and '2012-12-31' group by patientid",
		// now delete from *temp if Dx isn't AFTER intake visit
		"delete from temp" . $user . " from temp" . $user . " t, encValid e where t.patientid = e.patientid and e.encountertype = 1 and t.maxDate <= e.visitdate"
	)
);
 
?>
