<?php
$splashLabels_r = array (
"en" => array (
	"toClip" => "Copy to CSV"
	),
"fr" => array (
	"toClip" => "Copiez dans le .CSV"
	)
);
$waitMessageLabels = array(
	"en" => array("Loading, please wait..."),
	"fr" => array("En cours de chargement...")
);

$regGridlabels = array(
	'save' => array('en' => 'Save Updates', 'fr' => 'Sauvegarder'),
	'search' => array('en' => 'Patient ID search', 'fr' => "Rechercher le code d\'enr&ocirc;lement du patient"),
	'add' => array('en' => 'Add Patient Entry', 'fr' => 'Ajouter patient'),
	'more' => array('en' => 'Next 10 patients' , 'fr' => '10 patients suivants')
	);

$preARVlabels = array(
	"en" => array (
	"Date enrolled in HIV care",
	"Patient ID",
	"Last Name",
	"First name",
	"Birth Date",
	"Age",
	"less than 1 ",
	"1yr-2yrs",
	"2yrs-4yrs",
	"5yrs-14yrs",
	"15+",
	"Sex",
	"Pregnancy due date",
	"Address",
	"Confirmed HIV+ date",
	"CTX Start Date",
	"CTX Stop Date",
	"Date Detection I.O.",
	"Rx I.O Start Date",
	"Date Test Bacc",
	"+ Bacc result",
	"- Bacc result",
	"Date Test PPD",
	"+ PPD result",
	"- PPD result",
	"INH Start Date",
	"INH Stop Date",
	"Rx Anti-TB Start Date",
	"Rx Anti-TB Stop Date",
	"Fluconazole Start Date",
	"Fluconazole Stop Date",
	"WHO Stage I",
	"WHO Stage II",
	"WHO Stage III",
	"WHO Stage IV",
	"Date eligible for ARVs",
	"Reason for eligibility",
	"Date Eligible,Ready and Selected for ARV",
	"Last CD4 >= 3 months before start of ARV",
	"Date of patient death before ARV ",
	"Date of patient lost before ARV",
	"Date of patient transfer out before ARV",
	"ARV Start Date",
	"Clinical Stage at Start",
	"Patient Enrollment Code",
	"Section",
	"Town"),
	"fr" => array (
	"Date d\'Enrolment pour soins pallatifs",
	"Code d\'identification du patient",
	"Nom",
	"Pr&eacute;nom",
	"Date de naissance",
	"Age",
	"Moins 1 an",
	"1an-moins 2ans",
	"2ans-4ans",
	"5ans-14ans",
	"15 et +",
	"Sexe",
	"DPA",
	"Adresse/Commune",
	"Date Test VIH+",
	"CTX date d&eacute;but",
	"CTX date Fin",
	"Date Detection I.O.",
	"Rx I.O date d&eacute;but",
	"Date test bacc",
	"+ Resultat du test Bacc",
	"- Resutltat du test Bacc",
	"Date test PPD",
	"+ Resultat du test PPD",
	"- Resutltat du test PPD",
	"INH date d&eacute;but",
	"INH date fin",
	"Rx TB date d&eacute;but",
	"Rx TB date fin",
	"Antifongique date d&eacute;but",
	"Antifongique date fin",
	"OMS Stade I",
	"OMS Stade II",
	"OMS Stade III",
	"OMS Stade IV",
	"Date d\'eligibilite medicale a ARV",
	"Raison d\'eligibilite medicale",
	"Date eligible, pret et selectionne pour traitment ARV",
	"Dernier CD4 >= 3 mois avant d&eacute;but ARV",
	"Date si le patient est decede avant de commencer l\'ARV",
	"Date si le patient a desiste Avant le d&eacute;but d\'ARV",
	"Date si le patient transfere Avant le d&eacute;but d\'ARV",
	"Date d&eacute;but ARV",
	"Stade clinique au d&eacute;but de ARV",
	"Code d\'enr&ocirc;lement du patient",
	"Commune(D&eacute;partement)",
	"Localit&eacute;")
);

$ARVlabels = array(
	"en" => array(
	"ARV Start Date",
	"Patient ID",
	"Reason for eligibility",
	"Last Name",
	"First name",
	"Birth Date",
	"Age",
	"less than 1 ",
	"1yr-2yrs",
	"2yrs-4yrs",
	"5yrs-14yrs",
	"15+",
	"Sex",
	"Pregnancy due date",
	"Complete Address",
	"Functional Status",
	"Weight",
	"Height",
	"Clinical Stage",
	"Last CD4 >= 3 months before start of ARV",
	"INH Start Date",
	"INH Stop Date",
	"CTX Start Date",
	"CTX Stop Date",
	"Rx TB Start Date",
	"Rx TB Stop Date",
	"Date Detection I.O.",
	"1st line Regimen Initial",
	"1st Change Date (1st line)",
	"1st Change Reason (1st line)",
	"2nd Change Date (1st line)",
	"2nd Change Reason (1st line)",
	"2nd line Regimen Initial",
	"1st Change Date (2nd line)",
	"1st Change Reason (2nd line)",
	"2nd Change Date (2nd line)",
	"2nd Change Reason (2nd line)",
	"Patient Enrollment Code",
	"Month 0",
	"Month 1",
	"Month 2",
	"Month 3",
	"Month 4",
	"Month 5",
	"Functional Status month 6",
	"Month 6",
	"CD4 month 6",
	"Month 7",
	"Month 8",
	"Month 9",
	"Month 10",
	"Month 11",
	"Functional Status month 12",
	"Month 12",
	"CD4 month 12",
	"Month 13",
	"Month 14",
	"Month 15",
	"Month 16",
	"Month 17",
	"Month 18",
	"Month 19",
	"Month 20",
	"Month 21",
	"Month 22",
	"Month 23",
	"Functional Status month 24",
	"Month 24",
	"CD4 month 24",
	"Section",
	"Town"
	),
	"fr" => array(
	"Date d&eacute;but ARV",
	"Code d\'identification du patient",
	"Raison d\'&eacute;ligibilit&eacute; m&eacute;dicale",
	"Nom",
	"Prenom",
	"Date de naissance",
	"Age",
	"Moins 1 an",
	"1an-moins 2ans",
	"2ans-4ans",
	"5ans-14ans",
	"15 et +",
	"Sexe",
	"DPA",
	"Adresse compl&egrave;te",
	"Etat de fonctionnement",
	"Poids",
	"Taille",
	"Stade clinique",
	"Dernier CD4 >= 3 mois Avant Debut ARV",
	"INH date d&eacute;but",
	"INH date fin",
	"CTX date debut",
	"CTX date fin",
	"Rx TB date d&eacute;but",
	"Rx TB date fin",
	"Date detection I.O.",
	"1ere ligne regime initial",
	"1ere changement  (1ere ligne)",
	"1ere changement date (1ere ligne)",
	"2eme changement  (1ere ligne)",
	"2eme changement date (1ere ligne)",
	"2eme ligne regime initial",
	"1ere changement  (2eme ligne)",
	"1ere changement date (2eme ligne)",
	"2eme changement  (2eme ligne)",
	"2eme changement date (2eme ligne)",
	"Code d\'enr&ocirc;lement du Patient",
	"Mois 0",
	"Mois 1",
	"Mois 2",
	"Mois 3",
	"Mois 4",
	"Mois 5",
	"Etat de fonctionnement Mois 6",
	"Mois 6",
	"CD4 Mois 6",
	"Mois 7",
	"Mois 8",
	"Mois 9",
	"Mois 10",
	"Mois 11",
	"Etat de fonctionnement Mois 12",
	"Mois 12",
	"CD4 Mois 12",
	"Mois 13",
	"Mois 14",
	"Mois 15",
	"Mois 16",
	"Mois 17",
	"Mois 18",
	"Mois 19",
	"Mois 20",
	"Mois 21",
	"Mois 22",
	"Mois 23",
	"Etat de fonctionnement Mois 24",
	"Mois 24",
	"CD4 Mois 24",
	"Commune(D&eacute;partement)",
	"Localit&eacute;")
);
?>
