<?php

$splashLabels = array (
"en" => array (
	"title" => "Summary Information By Clinic",
	"clinic" => "Clinic",
	"sitecode" => "Code",
	"dbSite" => "Local<br />Server",
	"sLocal" => "Yes",
	"recent" => "Date of most<br />recently saved<br />form",
	"formCount" => "Form Count",
	"patientCount" => "Patient Count",
	"note1" => "Note: This table contains only clinics using the UW Server",
	"note2" => "Note: This table contains only clinics using this local server.",
	"artCount" => "ART",
	"clincCount" => "Clinic",
	"inClinic" => "Patients in clinic",
	"onART" => "Patients on ART",
	"total" => "Total",
	"new" => "New<br>A/E",
	"active" => "Active<br>A/E",
	"atRisk" => "At risk<br>A/E",
	"inactive" => "Inactive<br>A/E",
	"disc" => "Disc<br>A/E",
	"toClip" => "Copy to clipboard&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
	"copyComplete" => "Data copied to clipboard",
	"grandTotals" => "Grand Totals",
	"grandTotals2" => "Grand<br>Totals",
	"child" => "Child",
	"adult" => "Adult",
	"hivNeg" => "HIV -"
	),
"fr" => array (
	"title" => "Informations r&eacute;capitulatives  d'&eacute;tablissements",
	"clinic" => "&Eacute;tablissement",
	"sitecode" => "Code",
	"dbSite" => "Serveur<br />local",
	"sLocal" => "Oui",
	"recent" => "Date de saisie<br />la plus r&eacute;cente",
	"formCount" => "Compte de fiches",
	"patientCount" => "Compte de patients",
	"note1" => "Note : Cette table contient seulement des &eacute;tablissements &agrave; l'aide du serveur d'UW",
	"note2" => "Note: Cette table contient seulement des &eacute;tablissements &agrave; l'aide de ce serveur local.",
	"artCount" => "Compte de ART",
	"clinicCount" => "Compte de la &eacute;tablissement",
	"inClinic" => "Soins palliatifs",
	"onART" => "Sous TAR",
	"total" => "Total<br>A/E",
	"new" => "Nouveaux<br>A/E",
	"active" => "Actifs<br>A/E",
	"atRisk" => "Risque<br>A/E",
	"inactive" => "Inactifs<br>A/E",
	"disc" => "Disc<br>A/E",
	"toClip" => "Copiez dans le .CSV",
	"copyComplete" => "Donn&eacute;es copi&eacute;es &agrave; le presse-papiers",
	"grandTotals" => "Totaux généraux",
	"grandTotals2" => "Totaux<br>généraux",
	"child" => "Enfant",
	"adult" => "Adulte",
	"hivNeg" => "VIH -"
	)
);

?>
