<?php

$splashLabels = array (
"en" => array (
	"title" => "Summary Information By Clinic",
	"clinic" => "Clinic",
	"sitecode" => "Code",
	"dbSite" => "Local<br />Server",
	"sLocal" => "Yes",
	"recent" => "Date of most<br />recently saved<br />form",
	"minDate" => "Date of first<br />use",
	"formCount" => "Form Count",
	"patientCount" => "Patient Count",
	"note1" => "Note: This table contains only clinics using the ASP Server",
	"note2" => "Note: This table contains only clinics using this local server.",
	"artCount" => "ART",
	"clincCount" => "Clinic",
	"inClinic" => "Patients in clinic",
	"onART" => "Patients on ART",
	"total" => "Total",
	"preRecent" => "Recent <br>A/E",
	"preActive" => "Active<br>A/E",
	"preLost" => "Lost of follow up<br>A/E",
	"preTransf" => "Transfered<br>A/E",
	"preDeces" => "Death<br>A/E",
	
	"artRegulier" => "Regular <br>A/E",
	"artMissing" => "Missing appointment<br>A/E",
	"artLost" => "Lost of follow up<br>A/E",
	"artTransf" => "Transfered<br>A/E",
	"artStop" => "Stopped<br>A/E",
	"artDeces" => "Death<br>A/E",
	"toClip" => "Copy to clipboard&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",
	"copyComplete" => "Data copied to clipboard",
	"grandTotals" => "Grand Totals",
	"grandTotals2" => "Grand<br>Totals",
	"child" => "Child",
	"adult" => "Adult",
	"hivNeg" => "HIV -"
	),
"fr" => array (
	"title" => "Informations r&eacute;capitulatives  d'&eacute;tablissements",
	"clinic" => "&Eacute;tablissement",
	"sitecode" => "Code",
	"dbSite" => "Serveur<br />local",
	"sLocal" => "Oui",
	"recent" => "Date de saisie<br />la plus r&eacute;cente",
	"minDate" => "Date de<br />premiere<br />utilisation",
	"formCount" => "Compte de fiches",
	"patientCount" => "Compte de patients",
	"note1" => "Note : Cette table contient seulement des &eacute;tablissements &agrave; l'aide du serveur d'ASP",
	"note2" => "Note: Cette table contient seulement des &eacute;tablissements &agrave; l'aide de ce serveur local.",
	"artCount" => "Compte de ART",
	"clinicCount" => "Compte de la &eacute;tablissement",
	"inClinic" => "Soins palliatifs",
	"onART" => "Sous TAR",
	"total" => "Total<br>A/E",
	"preRecent" => "R&eacute;cent <br>A/E",
	"preActive" => "Actifs<br>A/E",
	"preLost" => "Perdu de vue<br>A/E",
	"preTransf" => "Transf&eacute;r&eacute;<br>A/E",
	"preDeces" => "D&eacute;c&eacute;d&eacute;<br>A/E",	
	"artRegulier" => "R&eacute;gulier <br>A/E",
	"artMissing" => "Randez-vous Rat&eacute;<br>A/E",
	"artLost" => "Perdu de Vue<br>A/E",
	"artTransf" => "Transf&eacute;r&eacute;<br>A/E",
	"artStop" => "Aret&eacute;<br>A/E",
	"artDeces" => "D&eacute;c&eacute;d&eacute;<br>A/E",
	
	
	"toClip" => "Copiez dans le .CSV",
	"copyComplete" => "Donn&eacute;es copi&eacute;es &agrave; le presse-papiers",
	"grandTotals" => "Totaux généraux",
	"grandTotals2" => "Totaux<br>généraux",
	"child" => "Enfant",
	"adult" => "Adulte",
	"hivNeg" => "VIH -"
	)
);

?>
