<?php
/**
 * Configuration defaults
 *
 * Do not edit this file.  Edit the settings in the config.php file, creating
 * the file if neccessary.
 *
 * @author	Svend Sorensen
 * @version	$Id: config.default.php 130 2006-10-22 08:42:51Z svends $
 */

/*
 * Hostname of LDAP server
 *
 * This can be a hostname, IP address, or LDAP URI (ldap://host, ldaps://host).
 */
$cfg['host'] = "localhost";

/*
 * Use TLS while connecting
 *
 * Either true or false.
 */
$cfg['use_tls'] = false;

/*
 * Authorization type
 *
 * Either config or session.  config uses the bind_dn and bind_pass set in the
 * configuration.  session displays a login form, and uses the values from the
 * form to log in.  session also allows logging out of the application.
 */
$cfg['auth_type'] = "config";

/*
 * DN for binding to server
 *
 * This DN should have write access to the children of the base_dn.  An
 * anonymous bind will be attempted if this variable is blank.
 */
$cfg['bind_dn'] = "";

/*
 * Password for binding to server
 */
$cfg['bind_pass'] = "";

/*
 * DN for LDAP base
 *
 * Accounts are created under this base.  If this variable is blank, the server
 * will be queried for the base DN.
 */
$cfg['base_dn'] = "";

/*
 * Password hashing algorithm
 *
 * One of crypt, ext_des, md5crypt, blowfish, md5, sha, smd5, ssha, or clear.
 * The sha, smd5, and ssha algorithms require PHP mhash support.
 */
$cfg['pw_hash'] = "md5";

/*
 * Default language
 *
 * See include/locale/ for installed languages.
 */
$cfg['lang'] = "en";
?>
