
DROP FUNCTION IF EXISTS IsNumeric;
CREATE FUNCTION IsNumeric RETURNS INTEGER SONAME 'udf_itech.so';

DROP FUNCTION IF EXISTS IsDate;
CREATE FUNCTION IsDate RETURNS INTEGER SONAME 'udf_itech.so';

DROP FUNCTION IF EXISTS ymdToDate;
CREATE FUNCTION ymdToDate RETURNS STRING SONAME 'udf_itech.so';
