DROP TABLE IF EXISTS healthQual;
go
CREATE TABLE healthQual (
  lastRun DATETIME,
  startDate DATETIME,
  endDate DATETIME,
  siteCode mediumint unsigned NULL,
  casesM mediumint unsigned NULL,
  casesF mediumint unsigned NULL,
  ind01_num_m mediumint unsigned NULL,
  ind01_num_f mediumint unsigned NULL,
  ind01_num_total mediumint unsigned NULL,
  ind01_den_m mediumint unsigned NULL,
  ind01_den_f mediumint unsigned NULL,
  ind01_den_total mediumint unsigned NULL,
  ind01_ratio_m VARCHAR(8) NULL,
  ind01_ratio_f VARCHAR(8) NULL,
  ind01_ratio_total VARCHAR(8) NULL,
  ind02_num_m mediumint unsigned NULL,
  ind02_num_f mediumint unsigned NULL,
  ind02_num_total mediumint unsigned NULL,
  ind02_den_m mediumint unsigned NULL,
  ind02_den_f mediumint unsigned NULL,
  ind02_den_total mediumint unsigned NULL,
  ind02_ratio_m VARCHAR(8) NULL,
  ind02_ratio_f VARCHAR(8) NULL,
  ind02_ratio_total VARCHAR(8) NULL,
  ind03_num_m mediumint unsigned NULL,
  ind03_num_f mediumint unsigned NULL,
  ind03_num_total mediumint unsigned NULL,
  ind03_den_m mediumint unsigned NULL,
  ind03_den_f mediumint unsigned NULL,
  ind03_den_total mediumint unsigned NULL,
  ind03_ratio_m VARCHAR(8) NULL,
  ind03_ratio_f VARCHAR(8) NULL,
  ind03_ratio_total VARCHAR(8) NULL,
  ind04_num_m mediumint unsigned NULL,
  ind04_num_f mediumint unsigned NULL,
  ind04_num_total mediumint unsigned NULL,
  ind04_den_m mediumint unsigned NULL,
  ind04_den_f mediumint unsigned NULL,
  ind04_den_total mediumint unsigned NULL,
  ind04_ratio_m VARCHAR(8) NULL,
  ind04_ratio_f VARCHAR(8) NULL,
  ind04_ratio_total VARCHAR(8) NULL,
  ind05_num_m mediumint unsigned NULL,
  ind05_num_f mediumint unsigned NULL,
  ind05_num_total mediumint unsigned NULL,
  ind05_den_m mediumint unsigned NULL,
  ind05_den_f mediumint unsigned NULL,
  ind05_den_total mediumint unsigned NULL,
  ind05_ratio_m VARCHAR(8) NULL,
  ind05_ratio_f VARCHAR(8) NULL,
  ind05_ratio_total VARCHAR(8) NULL,
  ind06_num_m mediumint unsigned NULL,
  ind06_num_f mediumint unsigned NULL,
  ind06_num_total mediumint unsigned NULL,
  ind06_den_m mediumint unsigned NULL,
  ind06_den_f mediumint unsigned NULL,
  ind06_den_total mediumint unsigned NULL,
  ind06_ratio_m VARCHAR(8) NULL,
  ind06_ratio_f VARCHAR(8) NULL,
  ind06_ratio_total VARCHAR(8) NULL,
  ind07_num_m mediumint unsigned NULL,
  ind07_num_f mediumint unsigned NULL,
  ind07_num_total mediumint unsigned NULL,
  ind07_den_m mediumint unsigned NULL,
  ind07_den_f mediumint unsigned NULL,
  ind07_den_total mediumint unsigned NULL,
  ind07_ratio_m VARCHAR(8) NULL,
  ind07_ratio_f VARCHAR(8) NULL,
  ind07_ratio_total VARCHAR(8) NULL,
  ind08_num_m mediumint unsigned NULL,
  ind08_num_f mediumint unsigned NULL,
  ind08_num_total mediumint unsigned NULL,
  ind08_den_m mediumint unsigned NULL,
  ind08_den_f mediumint unsigned NULL,
  ind08_den_total mediumint unsigned NULL,
  ind08_ratio_m VARCHAR(8) NULL,
  ind08_ratio_f VARCHAR(8) NULL,
  ind08_ratio_total VARCHAR(8) NULL,
  ind09_num_m mediumint unsigned NULL,
  ind09_num_f mediumint unsigned NULL,
  ind09_num_total mediumint unsigned NULL,
  ind09_den_m mediumint unsigned NULL,
  ind09_den_f mediumint unsigned NULL,
  ind09_den_total mediumint unsigned NULL,
  ind09_ratio_m VARCHAR(8) NULL,
  ind09_ratio_f VARCHAR(8) NULL,
  ind09_ratio_total VARCHAR(8) NULL,
  ind10_num_m mediumint unsigned NULL,
  ind10_num_f mediumint unsigned NULL,
  ind10_num_total mediumint unsigned NULL,
  ind10_den_m mediumint unsigned NULL,
  ind10_den_f mediumint unsigned NULL,
  ind10_den_total mediumint unsigned NULL,
  ind10_ratio_m VARCHAR(8) NULL,
  ind10_ratio_f VARCHAR(8) NULL,
  ind10_ratio_total VARCHAR(8) NULL,
  ind11_num_m mediumint unsigned NULL,
  ind11_num_f mediumint unsigned NULL,
  ind11_num_total mediumint unsigned NULL,
  ind11_den_m mediumint unsigned NULL,
  ind11_den_f mediumint unsigned NULL,
  ind11_den_total mediumint unsigned NULL,
  ind11_ratio_m VARCHAR(8) NULL,
  ind11_ratio_f VARCHAR(8) NULL,
  ind11_ratio_total VARCHAR(8) NULL,
  ind12_num_m mediumint unsigned NULL,
  ind12_num_f mediumint unsigned NULL,
  ind12_num_total mediumint unsigned NULL,
  ind12_den_m mediumint unsigned NULL,
  ind12_den_f mediumint unsigned NULL,
  ind12_den_total mediumint unsigned NULL,
  ind12_ratio_m VARCHAR(8) NULL,
  ind12_ratio_f VARCHAR(8) NULL,
  ind12_ratio_total VARCHAR(8) NULL,
  ind13_num_m mediumint unsigned NULL,
  ind13_num_f mediumint unsigned NULL,
  ind13_num_total mediumint unsigned NULL,
  ind13_den_m mediumint unsigned NULL,
  ind13_den_f mediumint unsigned NULL,
  ind13_den_total mediumint unsigned NULL,
  ind13_ratio_m VARCHAR(8) NULL,
  ind13_ratio_f VARCHAR(8) NULL,
  ind13_ratio_total VARCHAR(8) NULL,
  ind14_num_m mediumint unsigned NULL,
  ind14_num_f mediumint unsigned NULL,
  ind14_num_total mediumint unsigned NULL,
  ind14_den_m mediumint unsigned NULL,
  ind14_den_f mediumint unsigned NULL,
  ind14_den_total mediumint unsigned NULL,
  ind14_ratio_m VARCHAR(8) NULL,
  ind14_ratio_f VARCHAR(8) NULL,
  ind14_ratio_total VARCHAR(8) NULL,
  ind15_num_m mediumint unsigned NULL,
  ind15_num_f mediumint unsigned NULL,
  ind15_num_total mediumint unsigned NULL,
  ind15_den_m mediumint unsigned NULL,
  ind15_den_f mediumint unsigned NULL,
  ind15_den_total mediumint unsigned NULL,
  ind15_ratio_m VARCHAR(8) NULL,
  ind15_ratio_f VARCHAR(8) NULL,
  ind15_ratio_total VARCHAR(8) NULL,
  ind16_num_m mediumint unsigned NULL,
  ind16_num_f mediumint unsigned NULL,
  ind16_num_total mediumint unsigned NULL,
  ind16_den_m mediumint unsigned NULL,
  ind16_den_f mediumint unsigned NULL,
  ind16_den_total mediumint unsigned NULL,
  ind16_ratio_m VARCHAR(8) NULL,
  ind16_ratio_f VARCHAR(8) NULL,
  ind16_ratio_total VARCHAR(8) NULL,
  ind17_num_m mediumint unsigned NULL,
  ind17_num_f mediumint unsigned NULL,
  ind17_num_total mediumint unsigned NULL,
  ind17_den_m mediumint unsigned NULL,
  ind17_den_f mediumint unsigned NULL,
  ind17_den_total mediumint unsigned NULL,
  ind17_ratio_m VARCHAR(8) NULL,
  ind17_ratio_f VARCHAR(8) NULL,
  ind17_ratio_total VARCHAR(8) NULL,
  ind18_num_m mediumint unsigned NULL,
  ind18_num_f mediumint unsigned NULL,
  ind18_num_total mediumint unsigned NULL,
  ind18_den_m mediumint unsigned NULL,
  ind18_den_f mediumint unsigned NULL,
  ind18_den_total mediumint unsigned NULL,
  ind18_ratio_m VARCHAR(8) NULL,
  ind18_ratio_f VARCHAR(8) NULL,
  ind18_ratio_total VARCHAR(8) NULL,
  ind19_num_m mediumint unsigned NULL,
  ind19_num_f mediumint unsigned NULL,
  ind19_num_total mediumint unsigned NULL,
  ind19_den_m mediumint unsigned NULL,
  ind19_den_f mediumint unsigned NULL,
  ind19_den_total mediumint unsigned NULL,
  ind19_ratio_m VARCHAR(8) NULL,
  ind19_ratio_f VARCHAR(8) NULL,
  ind19_ratio_total VARCHAR(8) NULL,
  row_type TINYINT NULL,
  UNIQUE INDEX healthqualIndex (siteCode, startDate, endDate, row_type)
)
ENGINE = INNODB
CHARACTER SET utf8 COLLATE utf8_general_ci;
go
