DROP TABLE IF EXISTS dw_malaria_snapshot
go
CREATE TABLE IF NOT EXISTS dw_malaria_snapshot (
  visitdate date NOT NULL default '0000-00-00',
  patientid varchar(11) NOT NULL,
  malariaDxA tinyint(1) NOT NULL default '0',
  malariaDx tinyint(1) NOT NULL default '0',
  malariaDxG tinyint(1) NOT NULL default '0',
  malariaDxSuspectedA tinyint(1) NOT NULL default '0',
  malariaDxSuspected tinyint(1) NOT NULL default '0',
  malariaDxSuspectedG tinyint(1) NOT NULL default '0',
  isPregnant tinyint(1) NOT NULL default '0',
  sym_malariaLT tinyint(1) NOT NULL default '0',
  sym_malariaGT tinyint(1) NOT NULL default '0',
  feverLess2 tinyint(1) NOT NULL default '0',
  feverGreat2 tinyint(1) NOT NULL default '0',
  chloroquine tinyint(1) NOT NULL default '0',
  quinine tinyint(1) NOT NULL default '0',
  primaquine tinyint(1) NOT NULL default '0',
  convulsion tinyint(1) NOT NULL default '0',
  lethargy tinyint(1) NOT NULL default '0',
  hematuria tinyint(1) NOT NULL default '0',
  ictere tinyint(1) NOT NULL default '0',
  anemia tinyint(1) NOT NULL default '0',
  anemiaA tinyint(1) NOT NULL default '0',
  anemiaG tinyint(1) NOT NULL default '0',
  hemoglobine float NOT NULL default '5000',
  creatinine float NOT NULL default '5000',
  glycemie float NOT NULL default '5000',
  malariaTest tinyint(1) NOT NULL default '0',
  malariaTestRapid tinyint(1) NOT NULL default '0',
  rapidResultPositive tinyint(1) NOT NULL default '0',
  rapidResultNegative tinyint(1) NOT NULL default '0',
  smearResultPositive tinyint(1) NOT NULL default '0',
  smearResultNegative tinyint(1) NOT NULL default '0',
  testsOrdered  tinyint(1) NOT NULL default '0',
  hospitalisation tinyint(1) NOT NULL default '0',
  FT tinyint(1) NOT NULL default '0',
  FG tinyint(1) NOT NULL default '0',
  Vx tinyint(1) NOT NULL default '0',
  Ov tinyint(1) NOT NULL default '0',
  Mai tinyint(1) NOT NULL default '0',
  highTemp tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (visitdate,patientid),
  KEY pidIndex (patientid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
go