insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71610,'Rotavirus','rotavirusDtD1','Rotavirus','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71610,'Rotavirus','rotavirusDtD1','Rotavirus','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71611,'Rotavirus','rotavirusDtD2','Rotavirus','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71611,'Rotavirus','rotavirusDtD2','Rotavirus','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71612,'Varicelle','varicelDtD1','Varicelle','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71612,'Varicelle','varicelDtD1','Varicelle','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71613,'Varicelle','varicelDtD2','Varicelle','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71613,'Varicelle','varicelDtD2','Varicelle','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71614,'Typhimvi','typhimviDtD1','Typhimvi','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71614,'Typhimvi','typhimviDtD1','Typhimvi','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71615,'Typhimvi','typhimviDtD2','Typhimvi','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71615,'Typhimvi','typhimviDtD2','Typhimvi','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71616,'Pneumocoque','pneumocoqueDtD1','Pneumocoque','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71616,'Pneumocoque','pneumocoqueDtD1','Pneumocoque','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71617,'Pneumocoque','pneumocoqueDtD2','Pneumocoque','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71617,'Pneumocoque','pneumocoqueDtD2','Pneumocoque','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71618,'Pneumocoque','pneumocoqueDtD3','Pneumocoque','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71618,'Pneumocoque','pneumocoqueDtD3','Pneumocoque','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71619,'Hepatite A','hepatiteADtD1','Hepatite A','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71619,'Hepatite A','hepatiteADtD1','Hepatite A','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71620,'Hepatite A','hepatiteADtD2','Hepatite A','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71620,'Hepatite A','hepatiteADtD2','Hepatite A','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71621,'Menengo AC','menengoAcDtD1','Menengo AC','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71621,'Menengo AC','menengoAcDtD1','Menengo AC','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71622,'Menengo AC','menengoAcDtD2','Menengo AC','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71622,'Menengo AC','menengoAcDtD2','Menengo AC','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71623,'Cholera','choleraDtD1','Cholera','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71623,'Cholera','choleraDtD1','Cholera','fr','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71624,'Cholera','choleraDtD2','Cholera','en','1','2014-08-18');
insert into concept_name (concept_id,name,short_name,description,locale,creator,date_created) values (71624,'Cholera','choleraDtD2','Cholera','fr','1','2014-08-18');


insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71610','0','rotavirusDtD1','Rotavirus','Rotavirus','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71611','0','rotavirusDtD2','Rotavirus','Rotavirus','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71612','0','varicelDtD1','Varicelle','Varicelle','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71613','0','varicelDtD2','Varicelle','Varicelle','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71614','0','typhimviDtD1','Typhimvi','Typhimvi','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71615','0','typhimviDtD2','Typhimvi','Typhimvi','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71616','0','pneumocoqueDtD1','Pneumocoque','Pneumocoque','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71617','0','pneumocoqueDtD2','Pneumocoque','Pneumocoque','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71618','0','pneumocoqueDtD3','Pneumocoque','Pneumocoque','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71619','0','hepatiteADtD1','Hepatite A','Hepatite A','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71620','0','hepatiteADtD2','Hepatite A','Hepatite A','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71621','0','menengoAcDtD1','Menengo AC','Menengo AC','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71622','0','menengoAcDtD2','Menengo AC','Menengo AC','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71623','0','choleraDtD1','Cholera','Cholera','8','5','0','1','2014-08-18');
insert into concept (concept_id,retired,short_name,description,form_text,datatype_id,class_id,is_set,creator,date_created) values ('71624','0','choleraDtD2','Cholera','Cholera','8','5','0','1','2014-08-18');
