truncate table dw_malariaReportLookup;
INSERT INTO `dw_malariaReportLookup` (`indicator`, `indicatorType`, `nameen`, `namefr`, `definitionen`, `definitionfr`) VALUES
/* Total */
( 1, 1, 'Percentage of all patients with a fever of less than 2 weeks', 'Pourcentage de patients ayant eu la fièvre au cours des 2 dernières semaines (OMS)', 'Numerator: Number of fever cases <2 weeks Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas fébriles <2 semaines. Denominator: Nombre total de visites cliniques.'),
( 2, 1, 'Percentage of non-confirmed cases treated with either chloroquine, primaquine or quinine.', 'Pourcentage de patients avec fièvre (cas suspect) ayant reçu  un antipaludique (OMS)', 'Numerator: Number of patients who do not fit the definition of a confirmed case treated with either chloroquine, primaquine or quinine. Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas suspect ayant reçu un antipaludique. Denominator: Nombre total de visites cliniques.'),
( 3, 1, 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Number of confirmed cases treated with chloroquine and primaquine', 'Nombre de cas confirmés pour la malaria et mis sous traitement selon les normes- cas malaria simple'),
( 4, 1, 'Percentage of suspected cases tested.', 'Pourcentage de patients avec fièvre ayant été testés pour la malaria (OMS)','Numerator: Number of suspected cases with tests requested. Denominator:<b>Number of cases with fever or temperature > 37.5C.', 'Numerateur: Nombre de cas suspects de la malaria (fièvre) dépistée (test demande).<b>Denominateur : Nombre de cas fébriles <2 semaines ou Temp > 37.5C.'),
( 5, 0, 'Confirmed cases', 'Nombre de cas de la malaria confirmés', 'A clinical diagnosis of confirmed malaria or a positive malaria test whether rapid test or microscopy.', 'Impression clinique de Malaria (paludisme) confirmée ou test positif de malaria qu’il s’agisse d’une microscopie ou d’un test rapide.'),
( 6, 0, 'Patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria', 'Number of patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria'),
( 7, 0, 'Positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria', 'Number of positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria'),
( 8, 0, 'Patients with a positive microscopy test with plasmodium falciparum.', 'Nombre de patients ayant un test microscopique positif à Plasmodium falciparum.', '', ''),
( 9, 0, 'Patients with a positive microscopy test with plasmodium falciparum and another parasite, either Vx,Ov,Mal.', 'Nombre de patients ayant un test microscopique positif mixte à Plasmodium (OMS)', '', ''),
(10, 0, 'Patients with a positive microscopy test other than falciparum ', 'Nombre de patients ayant un test microscopique positif à Plasmodium autres que falciparum', '', ''),
(11, 0, 'Patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria', 'Number of patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria'),
(12, 0, 'Positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria', 'Number of positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria'),
(13, 0, 'Febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects de la malaria (fièvre) dépistée (test demande)','Number of febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects (fièvre) de malaria dépistée (test demande)'),
(14, 0, 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée', 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée'),
(15, 0, 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', '', ''),
(16, 0, 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés', 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés'),
/* pregnant */
(17, 1, 'Percentage of all patients with a fever of less than 2 weeks', 'Pourcentage de patients ayant eu la fièvre au cours des 2 dernières semaines (OMS)', 'Numerator: Number of fever cases <2 weeks Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas fébriles <2 semaines. Denominator: Nombre total de visites cliniques.'),
(18, 1, 'Percentage of non-confirmed cases treated with either chloroquine, primaquine or quinine.', 'Pourcentage de patients avec fièvre (cas suspect) ayant reçu  un antipaludique (OMS)', 'Numerator: Number of patients who do not fit the definition of a confirmed case treated with either chloroquine, primaquine or quinine. Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas suspect ayant reçu un antipaludique. Denominator: Nombre total de visites cliniques.'),
(19, 1, 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Number of confirmed cases treated with chloroquine and primaquine', 'Nombre de cas confirmés pour la malaria et mis sous traitement selon les normes- cas malaria simple'),
(20, 1, 'Percentage of suspected cases tested.', 'Pourcentage de patients avec fièvre ayant été testés pour la malaria (OMS)','Numerator: Number of suspected cases with tests requested. Denominator:<b>Number of cases with fever or temperature > 37.5C.', 'Numerateur: Nombre de cas suspects de la malaria (fièvre) dépistée (test demande).<b>Denominateur : Nombre de cas fébriles <2 semaines ou Temp > 37.5C.'),
(21, 0, 'Confirmed cases', 'Nombre de cas de la malaria confirmés', 'A clinical diagnosis of confirmed malaria or a positive malaria test whether rapid test or microscopy.', 'Impression clinique de Malaria (paludisme) confirmée ou test positif de malaria qu’il s’agisse d’une microscopie ou d’un test rapide.'),
(22, 0, 'Patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria', 'Number of patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria'),
(23, 0, 'Positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria', 'Number of positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria'),
(24, 0, 'Patients with a positive microscopy test with plasmodium falciparum.', 'Nombre de patients ayant un test microscopique positif à Plasmodium falciparum.', '', ''),
(25, 0, 'Patients with a positive microscopy test with plasmodium falciparum and another parasite, either Vx,Ov,Mal.', 'Nombre de patients ayant un test microscopique positif mixte à Plasmodium (OMS)', '', ''),
(26, 0, 'Patients with a positive microscopy test other than falciparum ', 'Nombre de patients ayant un test microscopique positif à Plasmodium autres que falciparum', '', ''),
(27, 0, 'Patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria', 'Number of patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria'),
(28, 0, 'Positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria', 'Number of positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria'),
(29, 0, 'Febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects de la malaria (fièvre) dépistée (test demande)','Number of febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects (fièvre) de malaria dépistée (test demande)'),
(30, 0, 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée', 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée'),
(31, 0, 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', '', ''),
(32, 0, 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés', 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés'),
/* < 1 year */
(33, 1, 'Percentage of all patients with a fever of less than 2 weeks', 'Pourcentage de patients ayant eu la fièvre au cours des 2 dernières semaines (OMS)', 'Numerator: Number of fever cases <2 weeks Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas fébriles <2 semaines. Denominator: Nombre total de visites cliniques.'),
(34, 1, 'Percentage of non-confirmed cases treated with either chloroquine, primaquine or quinine.', 'Pourcentage de patients avec fièvre (cas suspect) ayant reçu  un antipaludique (OMS)', 'Numerator: Number of patients who do not fit the definition of a confirmed case treated with either chloroquine, primaquine or quinine. Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas suspect ayant reçu un antipaludique. Denominator: Nombre total de visites cliniques.'),
(35, 1, 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Number of confirmed cases treated with chloroquine and primaquine', 'Nombre de cas confirmés pour la malaria et mis sous traitement selon les normes- cas malaria simple'),
(36, 1, 'Percentage of suspected cases tested.', 'Pourcentage de patients avec fièvre ayant été testés pour la malaria (OMS)','Numerator: Number of suspected cases with tests requested. Denominator:<b>Number of cases with fever or temperature > 37.5C.', 'Numerateur: Nombre de cas suspects de la malaria (fièvre) dépistée (test demande).<b>Denominateur : Nombre de cas fébriles <2 semaines ou Temp > 37.5C.'),
(37, 0, 'Confirmed cases', 'Nombre de cas de la malaria confirmés', 'A clinical diagnosis of confirmed malaria or a positive malaria test whether rapid test or microscopy.', 'Impression clinique de Malaria (paludisme) confirmée ou test positif de malaria qu’il s’agisse d’une microscopie ou d’un test rapide.'),
(38, 0, 'Patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria', 'Number of patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria'),
(39, 0, 'Positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria', 'Number of positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria'),
(40, 0, 'Patients with a positive microscopy test with plasmodium falciparum.', 'Nombre de patients ayant un test microscopique positif à Plasmodium falciparum.', '', ''),
(41, 0, 'Patients with a positive microscopy test with plasmodium falciparum and another parasite, either Vx,Ov,Mal.', 'Nombre de patients ayant un test microscopique positif mixte à Plasmodium (OMS)', '', ''),
(42, 0, 'Patients with a positive microscopy test other than falciparum ', 'Nombre de patients ayant un test microscopique positif à Plasmodium autres que falciparum', '', ''),
(43, 0, 'Patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria', 'Number of patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria'),
(44, 0, 'Positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria', 'Number of positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria'),
(45, 0, 'Febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects de la malaria (fièvre) dépistée (test demande)','Number of febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects (fièvre) de malaria dépistée (test demande)'),
(46, 0, 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée', 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée'),
(47, 0, 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', '', ''),
(48, 0, 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés', 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés'),
/* 1-4 years */
(49, 1, 'Percentage of all patients with a fever of less than 2 weeks', 'Pourcentage de patients ayant eu la fièvre au cours des 2 dernières semaines (OMS)', 'Numerator: Number of fever cases <2 weeks Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas fébriles <2 semaines. Denominator: Nombre total de visites cliniques.'),
(50, 1, 'Percentage of non-confirmed cases treated with either chloroquine, primaquine or quinine.', 'Pourcentage de patients avec fièvre (cas suspect) ayant reçu  un antipaludique (OMS)', 'Numerator: Number of patients who do not fit the definition of a confirmed case treated with either chloroquine, primaquine or quinine. Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas suspect ayant reçu un antipaludique. Denominator: Nombre total de visites cliniques.'),
(51, 1, 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Number of confirmed cases treated with chloroquine and primaquine', 'Nombre de cas confirmés pour la malaria et mis sous traitement selon les normes- cas malaria simple'),
(52, 1, 'Percentage of suspected cases tested.', 'Pourcentage de patients avec fièvre ayant été testés pour la malaria (OMS)','Numerator: Number of suspected cases with tests requested. Denominator:<b>Number of cases with fever or temperature > 37.5C.', 'Numerateur: Nombre de cas suspects de la malaria (fièvre) dépistée (test demande).<b>Denominateur : Nombre de cas fébriles <2 semaines ou Temp > 37.5C.'),
(53, 0, 'Confirmed cases', 'Nombre de cas de la malaria confirmés', 'A clinical diagnosis of confirmed malaria or a positive malaria test whether rapid test or microscopy.', 'Impression clinique de Malaria (paludisme) confirmée ou test positif de malaria qu’il s’agisse d’une microscopie ou d’un test rapide.'),
(54, 0, 'Patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria', 'Number of patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria'),
(55, 0, 'Positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria', 'Number of positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria'),
(56, 0, 'Patients with a positive microscopy test with plasmodium falciparum.', 'Nombre de patients ayant un test microscopique positif à Plasmodium falciparum.', '', ''),
(57, 0, 'Patients with a positive microscopy test with plasmodium falciparum and another parasite, either Vx,Ov,Mal.', 'Nombre de patients ayant un test microscopique positif mixte à Plasmodium (OMS)', '', ''),
(58, 0, 'Patients with a positive microscopy test other than falciparum ', 'Nombre de patients ayant un test microscopique positif à Plasmodium autres que falciparum', '', ''),
(59, 0, 'Patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria', 'Number of patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria'),
(60, 0, 'Positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria', 'Number of positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria'),
(61, 0, 'Febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects de la malaria (fièvre) dépistée (test demande)','Number of febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects (fièvre) de malaria dépistée (test demande)'),
(62, 0, 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée', 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée'),
(63, 0, 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', '', ''),
(64, 0, 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés', 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés'),
/* 5-9 years */
(65, 1, 'Percentage of all patients with a fever of less than 2 weeks', 'Pourcentage de patients ayant eu la fièvre au cours des 2 dernières semaines (OMS)', 'Numerator: Number of fever cases <2 weeks Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas fébriles <2 semaines. Denominator: Nombre total de visites cliniques.'),
(66, 1, 'Percentage of non-confirmed cases treated with either chloroquine, primaquine or quinine.', 'Pourcentage de patients avec fièvre (cas suspect) ayant reçu  un antipaludique (OMS)', 'Numerator: Number of patients who do not fit the definition of a confirmed case treated with either chloroquine, primaquine or quinine. Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas suspect ayant reçu un antipaludique. Denominator: Nombre total de visites cliniques.'),
(67, 1, 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Number of confirmed cases treated with chloroquine and primaquine', 'Nombre de cas confirmés pour la malaria et mis sous traitement selon les normes- cas malaria simple'),
(68, 1, 'Percentage of suspected cases tested.', 'Pourcentage de patients avec fièvre ayant été testés pour la malaria (OMS)','Numerator: Number of suspected cases with tests requested. Denominator:<b>Number of cases with fever or temperature > 37.5C.', 'Numerateur: Nombre de cas suspects de la malaria (fièvre) dépistée (test demande).<b>Denominateur : Nombre de cas fébriles <2 semaines ou Temp > 37.5C.'),
(69, 0, 'Confirmed cases', 'Nombre de cas de la malaria confirmés', 'A clinical diagnosis of confirmed malaria or a positive malaria test whether rapid test or microscopy.', 'Impression clinique de Malaria (paludisme) confirmée ou test positif de malaria qu’il s’agisse d’une microscopie ou d’un test rapide.'),
(70, 0, 'Patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria', 'Number of patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria'),
(71, 0, 'Positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria', 'Number of positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria'),
(72, 0, 'Patients with a positive microscopy test with plasmodium falciparum.', 'Nombre de patients ayant un test microscopique positif à Plasmodium falciparum.', '', ''),
(73, 0, 'Patients with a positive microscopy test with plasmodium falciparum and another parasite, either Vx,Ov,Mal.', 'Nombre de patients ayant un test microscopique positif mixte à Plasmodium (OMS)', '', ''),
(74, 0, 'Patients with a positive microscopy test other than falciparum ', 'Nombre de patients ayant un test microscopique positif à Plasmodium autres que falciparum', '', ''),
(75, 0, 'Patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria', 'Number of patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria'),
(76, 0, 'Positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria', 'Number of positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria'),
(77, 0, 'Febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects de la malaria (fièvre) dépistée (test demande)','Number of febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects (fièvre) de malaria dépistée (test demande)'),
(78, 0, 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée', 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée'),
(79, 0, 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', '', ''),
(80, 0, 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés', 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés'),
/* 10-14 years */
(81, 1, 'Percentage of all patients with a fever of less than 2 weeks', 'Pourcentage de patients ayant eu la fièvre au cours des 2 dernières semaines (OMS)', 'Numerator: Number of fever cases <2 weeks Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas fébriles <2 semaines. Denominator: Nombre total de visites cliniques.'),
(82, 1, 'Percentage of non-confirmed cases treated with either chloroquine, primaquine or quinine.', 'Pourcentage de patients avec fièvre (cas suspect) ayant reçu  un antipaludique (OMS)', 'Numerator: Number of patients who do not fit the definition of a confirmed case treated with either chloroquine, primaquine or quinine. Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas suspect ayant reçu un antipaludique. Denominator: Nombre total de visites cliniques.'),
(83, 1, 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Number of confirmed cases treated with chloroquine and primaquine', 'Nombre de cas confirmés pour la malaria et mis sous traitement selon les normes- cas malaria simple'),
(84, 1, 'Percentage of suspected cases tested.', 'Pourcentage de patients avec fièvre ayant été testés pour la malaria (OMS)','Numerator: Number of suspected cases with tests requested. Denominator:<b>Number of cases with fever or temperature > 37.5C.', 'Numerateur: Nombre de cas suspects de la malaria (fièvre) dépistée (test demande).<b>Denominateur : Nombre de cas fébriles <2 semaines ou Temp > 37.5C.'),
(85, 0, 'Confirmed cases', 'Nombre de cas de la malaria confirmés', 'A clinical diagnosis of confirmed malaria or a positive malaria test whether rapid test or microscopy.', 'Impression clinique de Malaria (paludisme) confirmée ou test positif de malaria qu’il s’agisse d’une microscopie ou d’un test rapide.'),
(86, 0, 'Patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria', 'Number of patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria'),
(87, 0, 'Positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria', 'Number of positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria'),
(88, 0, 'Patients with a positive microscopy test with plasmodium falciparum.', 'Nombre de patients ayant un test microscopique positif à Plasmodium falciparum.', '', ''),
(89, 0, 'Patients with a positive microscopy test with plasmodium falciparum and another parasite, either Vx,Ov,Mal.', 'Nombre de patients ayant un test microscopique positif mixte à Plasmodium (OMS)', '', ''),
(90, 0, 'Patients with a positive microscopy test other than falciparum ', 'Nombre de patients ayant un test microscopique positif à Plasmodium autres que falciparum', '', ''),
(91, 0, 'Patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria', 'Number of patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria'),
(92, 0, 'Positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria', 'Number of positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria'),
(93, 0, 'Febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects de la malaria (fièvre) dépistée (test demande)','Number of febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects (fièvre) de malaria dépistée (test demande)'),
(94, 0, 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée', 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée'),
(95, 0, 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', '', ''),
(96, 0, 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés', 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés'),
/* 15-24 years */ 
(97, 1, 'Percentage of all patients with a fever of less than 2 weeks', 'Pourcentage de patients ayant eu la fièvre au cours des 2 dernières semaines (OMS)', 'Numerator: Number of fever cases <2 weeks Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas fébriles <2 semaines. Denominator: Nombre total de visites cliniques.'),
(98, 1, 'Percentage of non-confirmed cases treated with either chloroquine, primaquine or quinine.', 'Pourcentage de patients avec fièvre (cas suspect) ayant reçu  un antipaludique (OMS)', 'Numerator: Number of patients who do not fit the definition of a confirmed case treated with either chloroquine, primaquine or quinine. Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas suspect ayant reçu un antipaludique. Denominator: Nombre total de visites cliniques.'),
(99, 1, 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Number of confirmed cases treated with chloroquine and primaquine', 'Nombre de cas confirmés pour la malaria et mis sous traitement selon les normes- cas malaria simple'),
(100, 1, 'Percentage of suspected cases tested.', 'Pourcentage de patients avec fièvre ayant été testés pour la malaria (OMS)','Numerator: Number of suspected cases with tests requested. Denominator:<b>Number of cases with fever or temperature > 37.5C.', 'Numerateur: Nombre de cas suspects de la malaria (fièvre) dépistée (test demande).<b>Denominateur : Nombre de cas fébriles <2 semaines ou Temp > 37.5C.'),
(101, 0, 'Confirmed cases', 'Nombre de cas de la malaria confirmés', 'A clinical diagnosis of confirmed malaria or a positive malaria test whether rapid test or microscopy.', 'Impression clinique de Malaria (paludisme) confirmée ou test positif de malaria qu’il s’agisse d’une microscopie ou d’un test rapide.'),
(102, 0, 'Patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria', 'Number of patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria'),
(103, 0, 'Positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria', 'Number of positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria'),
(104, 0, 'Patients with a positive microscopy test with plasmodium falciparum.', 'Nombre de patients ayant un test microscopique positif à Plasmodium falciparum.', '', ''),
(105, 0, 'Patients with a positive microscopy test with plasmodium falciparum and another parasite, either Vx,Ov,Mal.', 'Nombre de patients ayant un test microscopique positif mixte à Plasmodium (OMS)', '', ''),
(106, 0, 'Patients with a positive microscopy test other than falciparum ', 'Nombre de patients ayant un test microscopique positif à Plasmodium autres que falciparum', '', ''),
(107, 0, 'Patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria', 'Number of patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria'),
(108, 0, 'Positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria', 'Number of positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria'),
(109, 0, 'Febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects de la malaria (fièvre) dépistée (test demande)','Number of febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects (fièvre) de malaria dépistée (test demande)'),
(110, 0, 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée', 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée'),
(111, 0, 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', '', ''),
(112, 0, 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés', 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés'),
/* 25-49 years */ 
(113, 1, 'Percentage of all patients with a fever of less than 2 weeks', 'Pourcentage de patients ayant eu la fièvre au cours des 2 dernières semaines (OMS)', 'Numerator: Number of fever cases <2 weeks Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas fébriles <2 semaines. Denominator: Nombre total de visites cliniques.'),
(114, 1, 'Percentage of non-confirmed cases treated with either chloroquine, primaquine or quinine.', 'Pourcentage de patients avec fièvre (cas suspect) ayant reçu  un antipaludique (OMS)', 'Numerator: Number of patients who do not fit the definition of a confirmed case treated with either chloroquine, primaquine or quinine. Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas suspect ayant reçu un antipaludique. Denominator: Nombre total de visites cliniques.'),
(115, 1, 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Number of confirmed cases treated with chloroquine and primaquine', 'Nombre de cas confirmés pour la malaria et mis sous traitement selon les normes- cas malaria simple'),
(116, 1, 'Percentage of suspected cases tested.', 'Pourcentage de patients avec fièvre ayant été testés pour la malaria (OMS)','Numerator: Number of suspected cases with tests requested. Denominator:<b>Number of cases with fever or temperature > 37.5C.', 'Numerateur: Nombre de cas suspects de la malaria (fièvre) dépistée (test demande).<b>Denominateur : Nombre de cas fébriles <2 semaines ou Temp > 37.5C.'),
(117, 0, 'Confirmed cases', 'Nombre de cas de la malaria confirmés', 'A clinical diagnosis of confirmed malaria or a positive malaria test whether rapid test or microscopy.', 'Impression clinique de Malaria (paludisme) confirmée ou test positif de malaria qu’il s’agisse d’une microscopie ou d’un test rapide.'),
(118, 0, 'Patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria', 'Number of patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria'),
(119, 0, 'Positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria', 'Number of positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria'),
(120, 0, 'Patients with a positive microscopy test with plasmodium falciparum.', 'Nombre de patients ayant un test microscopique positif à Plasmodium falciparum.', '', ''),
(121, 0, 'Patients with a positive microscopy test with plasmodium falciparum and another parasite, either Vx,Ov,Mal.', 'Nombre de patients ayant un test microscopique positif mixte à Plasmodium (OMS)', '', ''),
(122, 0, 'Patients with a positive microscopy test other than falciparum ', 'Nombre de patients ayant un test microscopique positif à Plasmodium autres que falciparum', '', ''),
(123, 0, 'Patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria', 'Number of patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria'),
(124, 0, 'Positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria', 'Number of positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria'),
(125, 0, 'Febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects de la malaria (fièvre) dépistée (test demande)','Number of febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects (fièvre) de malaria dépistée (test demande)'),
(126, 0, 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée', 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée'),
(127, 0, 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', '', ''),
(128, 0, 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés', 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés'),
/* > 49 years */
(129, 1, 'Percentage of all patients with a fever of less than 2 weeks', 'Pourcentage de patients ayant eu la fièvre au cours des 2 dernières semaines (OMS)', 'Numerator: Number of fever cases <2 weeks Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas fébriles <2 semaines. Denominator: Nombre total de visites cliniques.'),
(130, 1, 'Percentage of non-confirmed cases treated with either chloroquine, primaquine or quinine.', 'Pourcentage de patients avec fièvre (cas suspect) ayant reçu  un antipaludique (OMS)', 'Numerator: Number of patients who do not fit the definition of a confirmed case treated with either chloroquine, primaquine or quinine. Denominator: number of total clinic visits for the time period.', 'Numerator: Nombre de cas suspect ayant reçu un antipaludique. Denominator: Nombre total de visites cliniques.'),
(131, 1, 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Pourcentage de patients  avec malaria confirmée ayant reçu un traitement conforme aux normes nationales du MSPP (OMS)', 'Number of confirmed cases treated with chloroquine and primaquine', 'Nombre de cas confirmés pour la malaria et mis sous traitement selon les normes- cas malaria simple'),
(132, 1, 'Percentage of suspected cases tested.', 'Pourcentage de patients avec fièvre ayant été testés pour la malaria (OMS)','Numerator: Number of suspected cases with tests requested. Denominator:<b>Number of cases with fever or temperature > 37.5C.', 'Numerateur: Nombre de cas suspects de la malaria (fièvre) dépistée (test demande).<b>Denominateur : Nombre de cas fébriles <2 semaines ou Temp > 37.5C.'),
(133, 0, 'Confirmed cases', 'Nombre de cas de la malaria confirmés', 'A clinical diagnosis of confirmed malaria or a positive malaria test whether rapid test or microscopy.', 'Impression clinique de Malaria (paludisme) confirmée ou test positif de malaria qu’il s’agisse d’une microscopie ou d’un test rapide.'),
(134, 0, 'Patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria', 'Number of patients tested with microscopy', 'Nombre de patients ayant bénéficié un test microscopique pour la malaria'),
(135, 0, 'Positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria', 'Number of positive microscopy results', 'Nombre de patients ayant un test microscopique positif pour la malaria'),
(136, 0, 'Patients with a positive microscopy test with plasmodium falciparum.', 'Nombre de patients ayant un test microscopique positif à Plasmodium falciparum.', '', ''),
(137, 0, 'Patients with a positive microscopy test with plasmodium falciparum and another parasite, either Vx,Ov,Mal.', 'Nombre de patients ayant un test microscopique positif mixte à Plasmodium (OMS)', '', ''),
(138, 0, 'Patients with a positive microscopy test other than falciparum ', 'Nombre de patients ayant un test microscopique positif à Plasmodium autres que falciparum', '', ''),
(139, 0, 'Patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria', 'Number of patients tested with rapid test', 'Nombre de patients ayant bénéficié d’un TDR pour la malaria'),
(140, 0, 'Positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria', 'Number of positive RDT results', 'Nombre de patients ayant un TDR positif pour la malaria'),
(141, 0, 'Febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects de la malaria (fièvre) dépistée (test demande)','Number of febrile cases < 2 weeks with tests ordered for malaria (microscopy or RDT)', 'Nombre de cas suspects (fièvre) de malaria dépistée (test demande)'),
(142, 0, 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée', 'Number of suspected cases confirmed', 'Nombre de cas suspects de la malaria confirmée'),
(143, 0, 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', 'Nombre de cas confirmés pour la malaria sévère et mis sous traitement selon les normes nationales du MSPP', '', ''),
(144, 0, 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés', 'Confirmed cases hospitalized', 'Nombre de patients avec Malaria hospitalisés'); 

update dw_malariaReportLookup set nameen = concat('T: ',     nameen), namefr = concat('T: ',    namefr), subGroupEn = 'Total'        , subGroupFr =  'Total'      where indicator between 1 and 16; 
update dw_malariaReportLookup set nameen = concat('P: ',     nameen), namefr = concat('P: ',    namefr), subGroupEn = 'Pregnant'     , subGroupFr =  'Enceintes'  where indicator between 17 and 32;
update dw_malariaReportLookup set nameen = concat('< 1: ',   nameen), namefr = concat('< 1: ',  namefr), subGroupEn = '< 1 years'    , subGroupFr =  '< 1 ans'    where indicator between 33 and 48;
update dw_malariaReportLookup set nameen = concat('1-4: ',   nameen), namefr = concat('1-4: ',  namefr), subGroupEn = '1-4 years'    , subGroupFr =  '1-4 ans'    where indicator between 49 and 64;
update dw_malariaReportLookup set nameen = concat('5-9: ',   nameen), namefr = concat('5-9: ',  namefr), subGroupEn = '5-9 years'    , subGroupFr =  '5-9 ans'    where indicator between 65 and 80;
update dw_malariaReportLookup set nameen = concat('10-14: ', nameen), namefr = concat('10-14:', namefr), subGroupEn = '10-14 years'  , subGroupFr =  '10-14 ans'  where indicator between 81 and 96;
update dw_malariaReportLookup set nameen = concat('15-24: ', nameen), namefr = concat('15-24:', namefr), subGroupEn = '15-24 years'  , subGroupFr =  '15-24 ans'  where indicator between 97 and 112;
update dw_malariaReportLookup set nameen = concat('25-49: ', nameen), namefr = concat('25-49:', namefr), subGroupEn = '25-49 years'  , subGroupFr =  '25-49 ans'  where indicator between 113 and 128;
update dw_malariaReportLookup set nameen = concat('>49: ',   nameen), namefr = concat('>49: ',  namefr), subGroupEn = '> 49 years'   , subGroupFr =  '> 49 ans'   where indicator between 129 and 144;

update dw_malariaReportLookup set indicatorDenominator = -1 where indicator in (1);
update dw_malariaReportLookup set indicatorDenominator = 1 where indicator in (2,4); 
update dw_malariaReportLookup set indicatorDenominator = 5 where indicator in (3);        
                              
update dw_malariaReportLookup set indicatorDenominator = -17 where indicator in (17);
update dw_malariaReportLookup set indicatorDenominator = 17 where indicator in (18,20);
update dw_malariaReportLookup set indicatorDenominator = 21 where indicator in (19); 
                                
update dw_malariaReportLookup set indicatorDenominator = -33 where indicator in (33);
update dw_malariaReportLookup set indicatorDenominator = 33 where indicator in (34,36); 
update dw_malariaReportLookup set indicatorDenominator = 37 where indicator in (35); 
                               
update dw_malariaReportLookup set indicatorDenominator = -49 where indicator in (49);
update dw_malariaReportLookup set indicatorDenominator = 49 where indicator in (50,52); 
update dw_malariaReportLookup set indicatorDenominator = 53 where indicator in (51);        
                               
update dw_malariaReportLookup set indicatorDenominator = -65 where indicator in (65); 
update dw_malariaReportLookup set indicatorDenominator = 65 where indicator in (66,68);         
update dw_malariaReportLookup set indicatorDenominator = 69 where indicator in (67);        
                               
update dw_malariaReportLookup set indicatorDenominator = -81 where indicator in (81);
update dw_malariaReportLookup set indicatorDenominator = 81 where indicator in (82,84);
update dw_malariaReportLookup set indicatorDenominator = 85 where indicator in (83);        
                                 
update dw_malariaReportLookup set indicatorDenominator = -97 where indicator in (97); 
update dw_malariaReportLookup set indicatorDenominator = 97 where indicator in (98,100); 
update dw_malariaReportLookup set indicatorDenominator = 101 where indicator in (99);        
                                
update dw_malariaReportLookup set indicatorDenominator = -113 where indicator in (113); 
update dw_malariaReportLookup set indicatorDenominator = 113 where indicator in (114,116); 
update dw_malariaReportLookup set indicatorDenominator = 117 where indicator in (115);        
                                 
update dw_malariaReportLookup set indicatorDenominator = -129 where indicator in (129);  
update dw_malariaReportLookup set indicatorDenominator = 129 where indicator in (130,132);
update dw_malariaReportLookup set indicatorDenominator = 133 where indicator in (131);        
